name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * SUN'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Datestamp
        run: echo "DATESTAMP=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        env:
          ubuntu_codename: noble
          ubuntu_version: 24.04
        with:
          build-args: |
            TAG=${{ env.ubuntu_codename }}
          platforms: |
            linux/amd64,
            linux/arm64
          push: true
          tags:
            scottyhardy/docker-remote-desktop:latest,
            scottyhardy/docker-remote-desktop:${{ env.DATESTAMP }},
            scottyhardy/docker-remote-desktop:ubuntu-${{ env.ubuntu_codename }},
            scottyhardy/docker-remote-desktop:ubuntu-${{ env.ubuntu_version }}

      - name: Update Docker Hub repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: scottyhardy/docker-remote-desktop
