name: test

on:
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v6
        env:
          ubuntu_codename: noble
        with:
          build-args: |
            TAG=${{ env.ubuntu_codename }}
